name: TitanGym - Desarrollo
values:
  - key: base_url
    value: 'https://localhost:8443'
  - key: api_version
    value: v1
  - key: token
    value: ''
  - key: user_id
    value: '1'
  - key: class_id
    value: '1'
  - key: service_id
    value: '1'
  - key: review_id
    value: '1'
  - key: image_id
    value: '1'
